name: Monthly Investment Notification

on:
  # Run on the 1st of every month at 00:00 UTC (9:00 AM JST)
  schedule:
    - cron: '0 0 1 * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calculation script
        id: calculate
        run: python src/AAVC_calculate_tool/notification_sender.py

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '【Monthly Investment Notification】AAVC Auto-Calculation Report'
          body: ${{ steps.calculate.outputs.notification_body }}
          to: ${{ secrets.MAIL_TO }}
          from: AAVC Calculate Tool
